hmrc/pillar2-frontend

test/controllers/eligibility/BusinessActivityUKControllerSpec.scala, test/controllers/eligibility/GroupTerritoriesControllerSpec.scala, test/controllers/eligibility/KBIneligibleControllerSpec.scala, test/controllers/eligibility/Kb750IneligibleControllerSpec.scala, test/controllers/eligibility/KbUKIneligibleControllerSpec.scala, test/controllers/eligibility/TurnOverEligibilityControllerSpec.scala, test/helpers/StubMessageControllerComponents.scala
Tested for all the eligibility questions
=> [PIL-272][JA]  Improve unit tests

app/views/bta/NoPlrIdGuidanceView.scala.html
=> [PIL-793] - resolve Absence of Anti-CSRF Tokens

app/assets/stylesheets/application.scss, app/views/RegistrationConfirmationView.scala.html, app/views/components/gds/govUkPanel.scala.html, app/views/components/gds/printLink.scala.html, conf/messages.en
Reverts hmrc/pillar2-frontend#225
=> [PIL-702] - Download feature on Reg confirmation page

app/controllers/bta/AccessConfirmationController.scala, app/views/bta/AccessConfirmationView.scala.html, app/views/bta/NoPlrIdGuidanceView.scala.html, conf/app.routes, conf/messages.en, test/controllers/bta/AccessConfirmationControllerSpec.scala
Reverts hmrc/pillar2-frontend#246
=> Revert "[PIL-838] - Remove confirmation page"

app/controllers/rfm/RfmContactCheckYourAnswersController.scala
For rfm contact check your answers controller pageload
=> [PIL-982] - use identity action

app/controllers/CheckYourAnswersController.scala, app/controllers/RegistrationWaitingRoomController.scala, test/controllers/CheckYourAnswersControllerSpec.scala
Use session repository to save subscription status.
=> [PIL-1091] - Data is not cleared after successful Registration

app/views/MakeAPaymentDashboardView.scala.html, test/views/MakeAPaymentDashboardViewSpec.scala
Added the link to the guidance page for the 'Make a payment' screen.
**NOTE** this change cannot be verified until the new link is live (See ticket for more info)
=> PIL-1085 - Link to Payment guidance

app/views/paymenthistory/TransactionHistoryView.scala.html, conf/messages.en, test/views/paymenthistory/TransactionHistoryViewSpec.scala
Reverts hmrc/pillar2-frontend#407 - merged in error, before QA
=> Revert "Pil 1116" - merged in error, before QA 

app/views/paymenthistory/TransactionHistoryView.scala.html, conf/messages.en, test/views/paymenthistory/TransactionHistoryViewSpec.scala
PIL-1116 #2 Pull Request  - after Revert
=> PIL-1116 #2 Pull Request  - after Revert 

app/views/subscriptionview/manageAccount/ManageGroupDetailsCheckYourAnswersView.scala.html
- Updated the view to use the library's flexible _Button_ model
- Added the _preventDoubleClick_ property
=> PIL-1446: Disable multiple clicks on amend group details page

.gitignore, app/controllers/subscription/manageAccount/ManageContactCannotReturnAfterConfirmationController.scala, app/controllers/subscription/manageAccount/ManageContactCheckYourAnswersController.scala, app/controllers/subscription/manageAccount/ManageContactDetailsWaitingRoomController.scala, app/models/subscription/ManageContactDetailsStatus.scala, app/pages/ManageContactDetailsStatusPage.scala, app/views/subscriptionview/manageAccount/ManageContactCannotReturnAfterConfirmationView.scala.html, app/views/subscriptionview/manageAccount/ManageContactDetailsWaitingRoomView.scala.html, conf/app.routes, conf/messages.en, project/AppDependencies.scala, project/metals.sbt, test/controllers/subscription/manageAccount/ManageContactCheckYourAnswersControllerSpec.scala, test/controllers/subscription/manageAccount/ManageContactDetailsWaitingRoomControllerSpec.scala, test/views/subscriptionview/manageAccount/ManageContactDetailsWaitingRoomViewSpec.scala
Add spinning wheel to amend contact details
=> Add spinning wheel to amend contact details

app/models/audit/GrsAuditEvent.scala, app/services/audit/AuditService.scala
Removed 'registeredinUK' field from 4 audit events
=> PIL-1751 : Removed 'registeredinUK' field from 4 audit events

app/controllers/TransactionHistoryController.scala, app/views/paymenthistory/NoTransactionHistoryView.scala.html, app/views/paymenthistory/TransactionHistoryView.scala.html, conf/messages.en, project/plugins.sbt, test/controllers/TransactionHistoryControllerSpec.scala, test/controllers/repayments/RepaymentsCheckYourAnswersControllerSpec.scala, test/views/paymenthistory/NoTransactionHistoryViewSpec.scala, test/views/paymenthistory/TransactionHistoryViewSpec.scala
Added "It will take up to 5 working days for payments to appear after each transaction." to transaction history page - also corrected surrounding content to be in line with updated prototype.
Transaction History page includes the link to the outstanding payments page (though not functional as page not built yet).
=> PIL-1811: Update Content on Transaction History Front-End Screen

conf/messages.en
Small fix to an existing error message relating to [PIL-1715](https://github.com/hmrc/pillar2-frontend/pull/443)
=> PIL-1715 - Fixed error message

app/controllers/repayments/RequestRefundBeforeStartController.scala, app/views/repayments/RequestRefundBeforeStartView.scala.html, conf/messages.en, project/AppDependencies.scala, test/controllers/repayments/RequestRefundBeforeStartControllerSpec.scala, test/views/repayments/RequestRefundBeforeStartViewSpec.scala
Content update for 'Request a refund' Guidance Page
Different content updated for agent's view.
Cleanup of unused messages
Update `play-conditional-form-mapping-play-30` version
=> PIL-1987: Content Update – 'Request a refund' Guidance Page

conf/application.conf
Changed to the new tracking code.
=> Updated to the latest Google Analytics tracking code

app/config/FrontendAppConfig.scala, app/views/AgentClientUnauthorisedView.scala.html, app/views/DashboardView.scala.html, app/views/components/gds/paragraphBodyLink.scala.html, app/views/registrationview/RegistrationConfirmationView.scala.html, build.sbt, conf/application.conf, conf/messages.en, project/AppDependencies.scala, project/plugins.sbt, test/helpers/ViewInstances.scala, test/views/DashboardViewSpec.scala, test/views/registration/RegistrationConfirmationViewSpec.scala
- Add a link to User Research to "Dashboard" and "Registration Complete" pages
- Updated coverage
=> PIL-2059 Added User Research Links to "Dashboard" and "Registration Complete" pages

build.sbt, project/AppDependencies.scala, project/plugins.sbt, test/controllers/CheckYourAnswersControllerSpec.scala, test/controllers/repayments/RepaymentsCheckYourAnswersControllerSpec.scala, test/controllers/rfm/RfmContactCheckYourAnswersControllerSpec.scala, test/controllers/subscription/manageAccount/ManageContactCheckYourAnswersControllerSpec.scala
These tests are continuously breaking the pr-builder and aren't trusted to test anything. They will be fixed in https://jira.tools.tax.service.gov.uk/browse/PIL-1872.
=> NOJIRA - Ignore flaky tests and fix scoverage exclusion

app/config/FrontendAppConfig.scala, app/views/outstandingpayments/OutstandingPaymentsView.scala.html, conf/application.conf, test/views/outstandingpayments/OutstandingPaymentsViewSpec.scala
Now we have the correct link, we should redirect to it. That's what this PR does.
=> [PIL-2309] - redirect to correct link

conf/application.conf, test/config/FrontendAppConfigSpec.scala
This PR is to revert the changes made in PIL-2411 branch. So old dashboard is enabled.
=> PIL-2411-PDS-revert to old dashboard in main
